### ISSUE TITLE
애니메이션 태그의 내용을 읽기가 너무 힘듭니다

### ISSUE THREAD

**Issue by sebanimm** [Team-INSERT/BUMAWIKI_WEB_V3#151]
눈이 침침해서 텍스트가 움직이니 잘 읽히지가 않습니다 ㅠㅠ
텍스트에 토글 형식으로 애니메이션을 껐다 켰다 할 수 있도록 하는 방안은 어떨까요?

추가적으로 현재 일부 태그를 사용할 때 마다 자동적으로 줄바꿈이 되는 현상이 있는데, 이는 의도된 부분인지 궁금합니다.
```md
// 입력
<어록>&quot;이래서 <링크 문서={이윤찬}>이윤찬</링크>이란..!&quot;</어록>

// 예상 출력
"이래서 이윤찬이란..!"

// 실제 출력
"이래서 
이윤찬
이란..!"
```

**Comment by Ubinquitous** [comment]
- 어록 태그와 블록 태그에 대한 줄바꿈은 수정 후 현재 작업 중인 `refactor/search` 브랜치의 PR이 올라갈 때 프로덕션 서버에 반영이 될 예정입니다.
- 토글 형식에 대해서는 조금 더 세부적으로 개선사항을 제시해주시면 큰 도움이 될 것 같습니다.

**Comment by sebanimm** [comment]
> * 어록 태그와 블록 태그에 대한 줄바꿈은 수정 후 현재 작업 중인 `refactor/search` 브랜치의 PR이 올라갈 때 프로덕션 서버에 반영이 될 예정입니다.
> * 토글 형식에 대해서는 조금 더 세부적으로 개선사항을 제시해주시면 큰 도움이 될 것 같습니다.

답변 감사합니다. 토글 형식은 애니메이션이 있는 태그에 state를 추가한 후 그것을 통해 class를 조작하여 애니메이션을 껐다 켰다 할 수 있도록 하는 방법을 생각하였습니다. 이 부분에 대해 어떻게 생각하시나요?

**Comment by Ubinquitous** [comment]
만약 state를 사용해야한다면 현재는 순수 HTML로 작성되어있던 코드들을 전부 컴포넌트로 바꾸고 이를 렌더링 시켜야 하기에
코드의 복잡성과 더불어 각 문서가 무거워질 수 있는 우려가 있다고 생각합니다.
아니면 애니메이션 속도를 낮추는 방안에 대해서는 어떻게 생각하시나요?

**Comment by sebanimm** [comment]
> 만약 state를 사용해야한다면 현재는 순수 HTML로 작성되어있던 코드들을 전부 컴포넌트로 바꾸고 이를 렌더링 시켜야 하기에 코드의 복잡성과 더불어 각 문서가 무거워질 수 있는 우려가 있다고 생각합니다. 아니면 애니메이션 속도를 낮추는 방안에 대해서는 어떻게 생각하시나요?

확실히 state를 사용하여 구현한다면 문서가 무거워질 우려가 있을 것 같습니다. 우빈님이 말씀해주신 것처럼 속도를 낮추는 절충안을 사용하는 편이 문서를 정적으로 유지하기 좋을 듯 하네요. state를 사용하지 않고 css의 `hover` 기능을 활용한다면 추가적인 자바스크립트 코드를 작성하지 않으면서, 문서 또한 서버 컴포넌트로 유지할 수 있을 것 같습니다!

**Comment by Ubinquitous** [comment]
좋은 것 같습니다 고려해보겠습니다!
